### ISSUE TITLE
Some inconsistencies in the documentation on github and xml

### ISSUE THREAD

**Issue by mcubillos** [PlinianCore/Documentation#1]
For example in https://github.com/pliniancore/documentation/wiki/FullDescriptionClass we have a AncillaryData for each element, but in the xml we have:
FullDescription
------FullDescriptionAtomized
-------------AncillaryData
------AncillaryData
------FullDescriptionUnstructured
------AncillaryData

**Comment by santiagomtzdelariva** [comment]
The first question is: What XML are you seeing? this question is very important to solve or explain this topic.

The FullDescription element can have two representations, Atomized and Unstructured, like all of elements of Plinian Core, both branchs have an AncillaryData element that represents  the extra information. The type of FullDescriptionAtomized is DetailType, this class is composed of two elements MeasurementOrFact and AncillaryData, you can see this in this link: https://github.com/PlinianCore/Documentation/wiki/DetailClass. The right structure would be:

FullDescription:
(sequence)
---------FullDescriptionAtomized
(DetailClass)
------------------MeassurementOrFact
------------------AncillaryData
---------AncillaryData
---------FullDescriptionUnstructured
---------AncillaryData

see the wiki page: https://github.com/pliniancore/documentation/wiki/FullDescriptionClass

If you want use the Atomized branch, It's mandatory the use of FullDescriptionAtomized and the same in the Unstructured branch, if you want to use it you have to use mandatorily the FullDescriptionUnstructured.

These rules that are defined in the XSD have to apply them in the XMLs files that you are producing.

I hope this clarify your doubt.
